version: '3'
services:
    mongo:
        image: mvertes/alpine-mongo
        expose:
            - "27017"
    flask:
        build: ./flask-backend
        expose:
            - "5000"
        depends_on:
            - mongo
        restart: always
    vue:
        build: ./vue-frontend
        ports:
            - "8080:8080"

